# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-19 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planetName', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Recrutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameRecrut', models.CharField(max_length=64)),
                ('nameRecruteAge', models.CharField(max_length=64)),
                ('planetRecruteEmail', models.CharField(max_length=64)),
                ('planetRecrute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localRecrutes', to='app.Planet')),
            ],
        ),
        migrations.CreateModel(
            name='Sith',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameSith', models.CharField(max_length=64)),
                ('planetSithTeaching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localSiths', to='app.Planet')),
            ],
        ),
    ]
