# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-19 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='planetName',
            field=models.CharField(max_length=64, verbose_name='Planet'),
        ),
        migrations.AlterField(
            model_name='recrutes',
            name='nameRecrut',
            field=models.CharField(max_length=64, verbose_name='Recrut'),
        ),
        migrations.AlterField(
            model_name='recrutes',
            name='nameRecruteAge',
            field=models.CharField(max_length=64, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='recrutes',
            name='planetRecruteEmail',
            field=models.CharField(max_length=64, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='sith',
            name='nameSith',
            field=models.CharField(max_length=64, verbose_name='Sith'),
        ),
    ]
