# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-21 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recrutes',
            name='nameRecruteAge',
        ),
        migrations.AddField(
            model_name='recrutes',
            name='recruteAge',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
