# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-24 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200321_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('optionYes', models.BooleanField()),
                ('optionNo', models.BooleanField()),
                ('answersTrueCount', models.IntegerField(default=0)),
                ('answersFalseCount', models.IntegerField(default=0)),
            ],
        ),
    ]
