# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-24 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200325_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='optionNoTrue',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='optionYesTrue',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='answerTrue',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='answerWrong',
            field=models.BooleanField(),
        ),
    ]
