# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-25 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200325_0213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='optionNoTrue',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='optionYesTrue',
        ),
        migrations.AddField(
            model_name='quiz',
            name='optionTruequestion',
            field=models.CharField(default='Yes', max_length=30),
        ),
    ]
