# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-29 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200325_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='sith',
            name='resrutesShadowing',
            field=models.ManyToManyField(blank=True, to='app.Recrutes'),
        ),
    ]
